name: kit_qr
description: A new Flutter package project.
publish_to: none
version: 0.0.2
homepage: null

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter:
    git:
      url: https://github.com/ukkoon/qr.flutter.git
      ref: custom-qr-fix-size

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
